### ISSUE TITLE
Does not work on Android 6.0 with Play Music v6.0.2005S

### ISSUE THREAD

**Issue by luka-grabarevic** [Arcus92/PlayMusicExporter#2]
Somehow GitHub does not let me upload the log file, so I'm pasting it here.

Debug [AppStart]: AndroidVersion: 6.0
Debug [AppStart]: AndroidSDK: 23
Debug [AppStart]: FilesDir: /data/user/0/de.arcus.playmusicexporter/files
Debug [DirectorySetup]: AppVersion: 66
Debug [DirectorySetup]: AppVersionName: 2.3.4
Debug [DirectorySetup]: StorageDirectorie[0]: /storage/emulated/0
Debug [DirectorySetup]: StorageDirectorie[1]: /mnt/sdcard
Debug [DirectorySetup]: PathExporterFiles: /data/user/0/de.arcus.playmusicexporter/files
Debug [DirectorySetup]: PathExporterTemp: /data/user/0/de.arcus.playmusicexporter/files/.tmp
Debug [DirectorySetup]: PathExporterDatabase: /data/user/0/de.arcus.playmusicexporter/files/.tmp/music.db
Debug [DirectorySetup]: PathPlayMusicDatabase: /data/user/0/com.google.android.music/databases/music.db
Debug [DirectorySetup]: PathPlayMusicDataMusic: /data/user/0/com.google.android.music/files/music
Debug [DirectorySetup]: PathPlayMusicExternalMusic[0]: /storage/emulated/0/Android/data/com.google.android.music/files/music
Debug [DirectorySetup]: PathPlayMusicExternalMusic[1]: /mnt/sdcard/Android/data/com.google.android.music/files/music
Debug [DirectorySetup]: PathPlayMusicExternalFiles[0]: /storage/emulated/0/Android/data/com.google.android.music/files
Debug [DirectorySetup]: PathPlayMusicExternalFiles[1]: /mnt/sdcard/Android/data/com.google.android.music/files
Debug [CreateDirectoryIfNotExist]: Directory already exists: /data/user/0/de.arcus.playmusicexporter/files/.tmp
Info [CheckRoot]: Start...
Info [SuOperation]: > echo roottest
Info [SuOperation]: < roottest
Info [FetchGoogleMusicDatabase]: Start...
Info [SuOperation]: > rm -f /data/user/0/de.arcus.playmusicexporter/files/.tmp/music.db
Info [SuOperation]: > cat /data/user/0/com.google.android.music/databases/music.db >> /data/user/0/de.arcus.playmusicexporter/files/.tmp/music.db
Info [SuOperation]: > chmod 0777 /data/user/0/de.arcus.playmusicexporter/files/.tmp/music.db
Info [FetchGoogleMusicArtworks]: Start...
Info [SuOperation]: > chmod 0755 /data/user/0/com.google.android.music/files/artwork2/folder/*
Info [SuOperation]: > chmod 0755 /data/user/0/com.google.android.music/files/artwork2/folder
Info [SuOperation]: > chmod 0755 /data/user/0/com.google.android.music/files/artwork2
Info [SuOperation]: > chmod 0755 /data/user/0/com.google.android.music/files
Error [PlayMusicDatabase]: Could not open PlayMusicDatabase: unknown error (code 14): Could not open database

**Comment by Arcus92** [comment]
Hi, yes there is a problem with Android 6.0. There is a new security feature that blocks the app to open a database from an other app. I will search for a workaround when i get Android 6.0 on my Nexus 4 (Cynogenmod) or Tablet. I hope this is not the end of my app. But there must be some trick to bypass this, i mean we got root! :-)

**Comment by luka-grabarevic** [comment]
Okay changing SELinux from Enforcing to Permissive did the job. Seems that I forget to switch it back after the 6.0 update. Wouldn't SELinux also be an issue on 5.0/5.1?

**Comment by forresthopkinsa** [comment]
If that's the solution, then why is this app incompatible with 6.0+?

**Comment by luka-grabarevic** [comment]
Don't know what problems do you exactly have, but the old PlayMusicExporter (haven't tested the new "beta") App works fine on my rooted Nexus 5 with latest 6.0 Update and SELinux set to Permissive Mode.

**Comment by forresthopkinsa** [comment]
I haven't even tried it because all of the documentation says it's incompat with 6.0 ..... I've been decrypting the files manually with @PlayMusicDecrypter ... it works pretty well (besides having to mess with the sqlite db) and I think I'll keep using it for now (so I can run it on my computer) but you guys have ought to update your documentation

**Comment by luka-grabarevic** [comment]
I'm not the maintainer of this repository, just another user. And I don't think the original developer will contribute anything further to this project as the last commit was nearly a year ago.
I assume this project here is abandoned.

**Comment by forresthopkinsa** [comment]
Ah, I see. Okay, thanks

**Comment by jcgruenhage** [comment]
The Maintainer has been away for a while :D See #8
