### ISSUE TITLE
Songs with a slash '/' fail to export

### ISSUE THREAD

**Issue by iffa** [Arcus92/PlayMusicExporter#4]
EDIT: They don't fail to export, they just become a part of the file path which confuses Windows especially

**Comment by 0x1cedd1ce** [comment]
It crashs with the Title "Regentropfen / Rosengarten".
A song with the title "3/4 Neun" exports without error, but it creates a new folder with the name "3" containing a file named "4 Neun.mp3".

Exception:

> PackageName: de.arcus.playmusicexporter2
> Crashed activity: activities.MusicTrackListActivity
> Exception: Attempt to invoke virtual method 'android.support.v4.provider.DocumentFile[] android.support.v4.provider.DocumentFile.listFiles()' on null object reference
> de.arcus.playmusiclib.PlayMusicManager.exportMusicTrack(PlayMusicManager.java:563)

**Comment by ddonuts4** [comment]
I fixed this, but I'm not sure if the dev is active enough to merge my [pull request](https://github.com/Arcus92/PlayMusicExporter/pull/9). I've created a release [on my fork](https://github.com/ddonuts4/PlayMusicExporter/releases) for anyone who wants this fix right away.

**Comment by Arcus92** [comment]
This is fixed. It had taken way too long.
